Fix Klockwork issues in the NTS code (#208)
* Fixing NTS ProtexIP issues

* Add pkt_generator files

* Make some tests passing

* New fixes

* Applied part of 4aa44a commit

* Fixed 'possible dereference of NULL pointer' KW issues (2 hits)

* Fixed 'possible dereference of NULL pointer' KW issues (3 hits)

* Fixed 'possible dereference of NULL pointer' KW issues (2 hits)

* Fixed 'possible dereference of NULL pointer' KW issues (multiple hits)

* Fixed 'possible dereference of NULL pointer' KW issues (multiple hits)

* Fixed 'Local variable returned through global variable' KW issue

* Fixed 'Buffer Overflow' KW issue

* Fixed 'possible memory leak' KW issues (5 occurrences)

* Fixed 'nes_dev_kni_alloc' function declaration related compilation issue

Compilation error message:
    /root/wally/appliance-ce/internal/nts/tests/..//daemon/io/nes_dev_kni.c:108:1: error: conflicting types for 'nes_dev_kni_alloc'
     nes_dev_kni_alloc(uint16_t port_id, const char* if_id)
     ^
    In file included from /root/wally/appliance-ce/internal/nts/tests/..//daemon/io/nes_dev_kni.c:41:0:
    ../nes_dev_kni_decl.h:21:17: note: previous declaration of 'nes_dev_kni_alloc' was here
     struct rte_kni *nes_dev_kni_alloc(uint16_t port_id);//, const char* if_id);

* Fixed 'format %02x expects type unsigned int, parameter 3 is uint8_t*' KW issue

* Added run-tests.sh script fix by Mouli